"""
HeroIntel Capture — lightweight Windows tray app

Two-capture flow per match:
  1. F9 on the rank progress screen  → uploads rank screenshot, waits
  2. F9 on the scoreboard screen     → uploads scoreboard, bundles both, notifies web app

Authentication:
  Device-code pairing through the web app — no password storage.

Anticheat safety (Blizzard Warden):
  - mss uses GDI BitBlt — same as OBS, Snipping Tool, Discord
  - Pure user-space, no kernel driver, no process injection
  - Never attaches to or reads from the Overwatch process
  - keyboard.add_hotkey uses Win32 RegisterHotKey (user-space)
"""

import io
import json
import os
import sys
import time
import threading
import webbrowser
import tkinter as tk
from collections import deque
from tkinter import messagebox
from pathlib import Path
from datetime import datetime, timezone

import requests
import keyring

try:
    import mss
    from PIL import Image
    import pystray
    from pystray import MenuItem as item
    import keyboard
    import customtkinter as ctk
except ImportError as e:
    print(f"Missing dependency: {e}")
    print("Run: pip install mss Pillow pystray keyboard keyring requests customtkinter")
    sys.exit(1)

# Build-time constants. Generated by build.bat from ../.env.local.
# In dev mode falls back to _constants.example.py if a real one isn't present.
try:
    from _constants import (  # type: ignore
        FIREBASE_API_KEY,
        FIREBASE_PROJECT_ID,
        FIREBASE_STORAGE_BUCKET,
        WEB_APP_URL,
    )
except ImportError:
    try:
        from _constants_example import (  # type: ignore
            FIREBASE_API_KEY,
            FIREBASE_PROJECT_ID,
            FIREBASE_STORAGE_BUCKET,
            WEB_APP_URL,
        )
    except ImportError:
        print("Missing _constants.py — run build.bat or copy _constants.example.py")
        sys.exit(1)

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("dark-blue")

# ── Config ─────────────────────────────────────────────────────────────────────

APP_NAME = "HeroIntelCapture"
APP_VERSION = "1.1.0"
APPDATA = os.environ.get("APPDATA", str(Path.home()))
CONFIG_DIR = Path(APPDATA) / APP_NAME
CONFIG_FILE = CONFIG_DIR / "config.json"
KEYRING_SERVICE = APP_NAME
KEYRING_REFRESH_KEY = "refresh_token"

# ── Global state ───────────────────────────────────────────────────────────────

_config: dict = {}
_id_token: str = ""
_token_expiry: float = 0.0

# Two-phase capture state
_capture_state: str = "idle"          # "idle" | "waiting_scoreboard"
_pending_doc_id: str = ""             # Firestore doc ID waiting for scoreboard
_pending_rank_url: str = ""           # rank progress download URL (for display)

# Rolling history of recent captures shown in the home window.
_recent: "deque[dict]" = deque(maxlen=5)

# CTk root (main thread)
_tk_root: "ctk.CTk | None" = None

# UI handles updated from any thread via root.after()
_sv_state: "tk.StringVar | None" = None
_sv_status: "tk.StringVar | None" = None
_status_label: "ctk.CTkLabel | None" = None
_recent_frame: "ctk.CTkFrame | None" = None
_cancel_btn: "ctk.CTkButton | None" = None
_sv_instructions: "tk.StringVar | None" = None

# Tray + hotkey handles
_tray_icon: "pystray.Icon | None" = None
_current_hotkey: str = ""
_current_cancel_hotkey: str = ""

# Cached CTkImage of the logo (created lazily after the root exists)
_logo_image_cache: "dict[int, ctk.CTkImage]" = {}

# ── Config helpers ─────────────────────────────────────────────────────────────

def load_config() -> dict:
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return {}

def save_config(cfg: dict):
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)

# ── Windows autostart (HKCU\…\Run registration) ───────────────────────────────

_AUTOSTART_KEY  = r"Software\Microsoft\Windows\CurrentVersion\Run"
_AUTOSTART_NAME = "HeroIntelCapture"

def _autostart_target() -> str:
    """Command line stored in HKCU Run. EXE path when frozen, else python+main.py."""
    if getattr(sys, "frozen", False):
        return f'"{sys.executable}"'
    return f'"{sys.executable}" "{Path(__file__).resolve()}"'

def is_autostart_enabled() -> bool:
    if sys.platform != "win32":
        return False
    try:
        import winreg
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _AUTOSTART_KEY, 0, winreg.KEY_READ) as key:
            value, _ = winreg.QueryValueEx(key, _AUTOSTART_NAME)
            return bool(value)
    except OSError:
        return False
    except Exception:
        return False

def set_autostart(enabled: bool) -> bool:
    """Enable or disable launch-on-login. Returns True on success."""
    if sys.platform != "win32":
        return False
    try:
        import winreg
        if enabled:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _AUTOSTART_KEY, 0, winreg.KEY_WRITE) as key:
                winreg.SetValueEx(key, _AUTOSTART_NAME, 0, winreg.REG_SZ, _autostart_target())
        else:
            try:
                with winreg.OpenKey(winreg.HKEY_CURRENT_USER, _AUTOSTART_KEY, 0, winreg.KEY_WRITE) as key:
                    winreg.DeleteValue(key, _AUTOSTART_NAME)
            except FileNotFoundError:
                pass  # already absent
        return True
    except Exception as e:
        print(f"[autostart] failed: {e}")
        return False

# ── Resource path (handles PyInstaller --onefile) ──────────────────────────────

def _resource_path(name: str) -> Path:
    if getattr(sys, "frozen", False):
        return Path(getattr(sys, "_MEIPASS", "")) / name
    return Path(__file__).parent / name


def _claim_app_identity():
    """Windows: register an explicit AppUserModelID so the OS shows our taskbar
    icon (and groups our windows separately from Python.exe). Without this,
    `python main.py` displays the Python interpreter's icon on the taskbar."""
    if sys.platform != "win32":
        return
    try:
        import ctypes
        ctypes.windll.shell32.SetCurrentProcessExplicitAppUserModelID(
            "HeroIntel.Capture")
    except Exception:
        pass


def _get_logo_image(size: int) -> "ctk.CTkImage | None":
    """Return a cached CTkImage of the square brand mark at the given size."""
    key = ("icon", size)
    if key in _logo_image_cache:
        return _logo_image_cache[key]
    path = _resource_path("icon.png")
    if not path.exists():
        return None
    try:
        img = Image.open(path).convert("RGBA")
        ctk_img = ctk.CTkImage(light_image=img, dark_image=img, size=(size, size))
        _logo_image_cache[key] = ctk_img
        return ctk_img
    except Exception:
        return None


def _get_wordmark_image(height: int) -> "ctk.CTkImage | None":
    """Return a cached CTkImage of the wide wordmark logo (logo3) at the given
    height, scaled to preserve aspect ratio."""
    key = ("wordmark", height)
    if key in _logo_image_cache:
        return _logo_image_cache[key]
    path = _resource_path("wordmark.png")
    if not path.exists():
        # Fall back to the square mark so headers still render.
        return _get_logo_image(height)
    try:
        img = Image.open(path).convert("RGBA")
        w, h = img.size
        scaled_w = max(1, int(w * (height / h)))
        ctk_img = ctk.CTkImage(light_image=img, dark_image=img, size=(scaled_w, height))
        _logo_image_cache[key] = ctk_img
        return ctk_img
    except Exception:
        return None


_icon_photo_cache: list = []     # keep PhotoImage refs alive for the GC
_icon_hicon_cache: list = []     # keep HICON handles alive for the process

# Win32 constants
_WM_SETICON      = 0x0080
_ICON_SMALL      = 0
_ICON_BIG        = 1
_ICON_SMALL2     = 2
_IMAGE_ICON      = 1
_LR_LOADFROMFILE = 0x00000010
_LR_DEFAULTSIZE  = 0x00000040


def _win_set_icon(window):
    """Bypass Tcl's iconbitmap (which silently fails inside PyInstaller's
    _MEIPASS temp dir) and send WM_SETICON straight to the HWND."""
    if sys.platform != "win32":
        return
    ico = _resource_path("icon.ico")
    if not ico.exists():
        return
    try:
        import ctypes
        from ctypes import wintypes
        user32 = ctypes.windll.user32

        # Resolve window's HWND. Tk widgets sit inside a frame; the HWND we
        # actually want is the top-level parent of winfo_id().
        hwnd = wintypes.HWND(int(window.winfo_id()))
        # Walk up to the toplevel that owns the taskbar entry.
        GA_ROOT = 2
        get_ancestor = user32.GetAncestor
        get_ancestor.restype = wintypes.HWND
        get_ancestor.argtypes = [wintypes.HWND, ctypes.c_uint]
        top_hwnd = get_ancestor(hwnd, GA_ROOT) or hwnd

        load_image = user32.LoadImageW
        load_image.restype = wintypes.HANDLE
        load_image.argtypes = [
            wintypes.HINSTANCE, wintypes.LPCWSTR, wintypes.UINT,
            ctypes.c_int, ctypes.c_int, wintypes.UINT,
        ]
        send_message = user32.SendMessageW
        send_message.restype = ctypes.c_ssize_t
        send_message.argtypes = [
            wintypes.HWND, wintypes.UINT, ctypes.c_ssize_t, ctypes.c_ssize_t
        ]

        path = str(ico)
        small = load_image(None, path, _IMAGE_ICON, 16, 16, _LR_LOADFROMFILE)
        big   = load_image(None, path, _IMAGE_ICON, 32, 32, _LR_LOADFROMFILE)
        if small:
            _icon_hicon_cache.append(small)
            send_message(top_hwnd, _WM_SETICON, _ICON_SMALL, small)
            send_message(top_hwnd, _WM_SETICON, _ICON_SMALL2, small)
        if big:
            _icon_hicon_cache.append(big)
            send_message(top_hwnd, _WM_SETICON, _ICON_BIG, big)
    except Exception as e:
        print(f"[icon] WM_SETICON failed: {e}")


def _force_dark_titlebar(window):
    """Apply DWM dark mode to the window's title bar on Windows 10/11.
    CTkToplevel only applies this on FocusIn, which fires after the window has
    already been painted with the light OS theme — causing a flash. Calling
    this synchronously before the window becomes visible eliminates that flash."""
    if sys.platform != "win32":
        return
    try:
        import ctypes
        from ctypes import wintypes
        hwnd = wintypes.HWND(int(window.winfo_id()))
        GA_ROOT = 2
        get_ancestor = ctypes.windll.user32.GetAncestor
        get_ancestor.restype = wintypes.HWND
        get_ancestor.argtypes = [wintypes.HWND, ctypes.c_uint]
        top_hwnd = get_ancestor(hwnd, GA_ROOT) or hwnd

        DWMWA_USE_IMMERSIVE_DARK_MODE = 20      # Win10 1903+ / Win11
        DWMWA_USE_IMMERSIVE_DARK_MODE_OLD = 19  # Win10 1809
        value = ctypes.c_int(1)
        dwm = ctypes.windll.dwmapi
        if dwm.DwmSetWindowAttribute(
            top_hwnd, DWMWA_USE_IMMERSIVE_DARK_MODE,
            ctypes.byref(value), ctypes.sizeof(value)
        ) != 0:
            dwm.DwmSetWindowAttribute(
                top_hwnd, DWMWA_USE_IMMERSIVE_DARK_MODE_OLD,
                ctypes.byref(value), ctypes.sizeof(value)
            )
    except Exception:
        pass


def _prepare_dialog(dlg):
    """Hide a freshly-created CTk window before it paints, force a dark title
    bar, and apply our icon — all synchronously. Caller must invoke
    `_reveal_dialog(dlg)` once the window is fully built."""
    try:
        # alpha=0 is applied by Windows DWM before the first frame is shown,
        # so the window never flashes white during construction.
        dlg.attributes("-alpha", 0.0)
    except Exception:
        pass
    try:
        dlg.withdraw()
    except Exception:
        pass
    _force_dark_titlebar(dlg)
    _apply_window_icon(dlg)


def _reveal_dialog(dlg):
    """Show a dialog prepared with `_prepare_dialog` once it's fully built."""
    try:
        dlg.update_idletasks()
        dlg.deiconify()
        dlg.lift()
        dlg.attributes("-alpha", 1.0)
    except Exception:
        pass


def _apply_window_icon(window):
    """Set the window/taskbar/title-bar icon. Layered approach:
       1. Tcl iconphoto (works in dev, sets default for child toplevels)
       2. Tcl iconbitmap (Win11 title-bar polish)
       3. Win32 WM_SETICON (the only one that survives PyInstaller --onefile)
    """
    png = _resource_path("icon.png")
    ico = _resource_path("icon.ico")

    if png.exists():
        try:
            from PIL import ImageTk
            img = Image.open(png).convert("RGBA")
            photos = []
            for size in (16, 24, 32, 48, 64):
                photos.append(ImageTk.PhotoImage(img.resize((size, size), Image.LANCZOS)))
            _icon_photo_cache.extend(photos)
            window.iconphoto(True, *photos)
        except Exception as e:
            print(f"[icon] iconphoto failed: {e}")

    if ico.exists():
        try:
            window.iconbitmap(default=str(ico))
        except Exception:
            try:
                window.iconbitmap(str(ico))
            except Exception:
                pass

    # Win32 path — must run after the window has an HWND. We schedule it once
    # immediately and again on <Map> in case the HWND wasn't created yet.
    def _set_now(_evt=None):
        try:
            window.update_idletasks()
        except Exception:
            pass
        _win_set_icon(window)
    window.after(0, _set_now)
    try:
        window.bind("<Map>", _set_now, add="+")
    except Exception:
        pass


def _position_near(dlg, parent):
    """Center `dlg` over `parent` using its requested geometry."""
    if parent is None:
        return
    try:
        parent.update_idletasks()
        dlg.update_idletasks()
        px = parent.winfo_x()
        py = parent.winfo_y()
        pw = parent.winfo_width()
        ph = parent.winfo_height()
        dw = dlg.winfo_reqwidth()
        dh = dlg.winfo_reqheight()
        x = max(0, px + (pw - dw) // 2)
        y = max(0, py + (ph - dh) // 2)
        dlg.geometry(f"+{x}+{y}")
    except Exception:
        pass

# ── Firebase REST auth ─────────────────────────────────────────────────────────

_CUSTOM_TOKEN_URL = "https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key={key}"
_REFRESH_URL = "https://securetoken.googleapis.com/v1/token?key={key}"

def sign_in_custom_token(custom_token: str) -> tuple:
    """Exchange a Firebase custom token for an idToken + refreshToken."""
    r = requests.post(
        _CUSTOM_TOKEN_URL.format(key=FIREBASE_API_KEY),
        json={"token": custom_token, "returnSecureToken": True},
        timeout=15,
    )
    r.raise_for_status()
    d = r.json()
    return d["idToken"], d["refreshToken"]

def _refresh(refresh_token: str) -> tuple:
    r = requests.post(
        _REFRESH_URL.format(key=FIREBASE_API_KEY),
        data={"grant_type": "refresh_token", "refresh_token": refresh_token},
        timeout=10,
    )
    r.raise_for_status()
    d = r.json()
    return d["id_token"], time.time() + int(d.get("expires_in", 3600)) - 60

def get_valid_token() -> str:
    global _id_token, _token_expiry
    if _id_token and time.time() < _token_expiry:
        return _id_token
    rt = keyring.get_password(KEYRING_SERVICE, KEYRING_REFRESH_KEY)
    if not rt:
        raise RuntimeError("Not paired. Open Settings → Pair desktop.")
    _id_token, _token_expiry = _refresh(rt)
    return _id_token

# ── Device pairing ─────────────────────────────────────────────────────────────

def _pairing_url(path: str) -> str:
    return WEB_APP_URL.rstrip("/") + path

def initiate_pairing() -> dict:
    r = requests.post(_pairing_url("/api/devices/initiate"), timeout=15)
    r.raise_for_status()
    return r.json()

def poll_pairing(pairing_token: str) -> dict:
    r = requests.get(
        _pairing_url("/api/devices/poll"),
        params={"token": pairing_token},
        timeout=15,
    )
    if r.status_code in (404, 410):
        return {"status": "expired"}
    r.raise_for_status()
    return r.json()

# ── Firebase Storage upload ────────────────────────────────────────────────────

def upload_screenshot(jpeg_bytes: bytes, storage_path: str, token: str) -> str:
    encoded = requests.utils.quote(storage_path, safe="")
    url = f"https://firebasestorage.googleapis.com/v0/b/{FIREBASE_STORAGE_BUCKET}/o?uploadType=media&name={encoded}"
    r = requests.post(url, data=jpeg_bytes,
                      headers={"Authorization": f"Bearer {token}", "Content-Type": "image/jpeg"},
                      timeout=30)
    r.raise_for_status()
    dl_token = r.json().get("downloadTokens", "")
    return f"https://firebasestorage.googleapis.com/v0/b/{FIREBASE_STORAGE_BUCKET}/o/{encoded}?alt=media&token={dl_token}"

# ── Firestore REST ─────────────────────────────────────────────────────────────

_FS_BASE = "https://firestore.googleapis.com/v1/projects/{proj}/databases/(default)/documents"

def _fs_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}

def create_pending_match(uid: str, rank_url: str, rank_path: str, token: str) -> str:
    url = f"{_FS_BASE.format(proj=FIREBASE_PROJECT_ID)}/users/{uid}/pendingScreenshots"
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    body = {"fields": {
        "rankProgressUrl":  {"stringValue": rank_url},
        "rankProgressPath": {"stringValue": rank_path},
        "scoreboardUrl":    {"nullValue": None},
        "scoreboardPath":   {"nullValue": None},
        "uploadedAt":       {"timestampValue": now},
        "status":           {"stringValue": "waiting_scoreboard"},
        "consumed":         {"booleanValue": False},
    }}
    r = requests.post(url, json=body, headers=_fs_headers(token), timeout=10)
    r.raise_for_status()
    return r.json()["name"].split("/")[-1]

def complete_pending_match(uid: str, doc_id: str, sb_url: str, sb_path: str, token: str):
    doc_path = f"users/{uid}/pendingScreenshots/{doc_id}"
    url = (
        f"{_FS_BASE.format(proj=FIREBASE_PROJECT_ID)}/{doc_path}"
        "?updateMask.fieldPaths=scoreboardUrl"
        "&updateMask.fieldPaths=scoreboardPath"
        "&updateMask.fieldPaths=status"
    )
    body = {"fields": {
        "scoreboardUrl":  {"stringValue": sb_url},
        "scoreboardPath": {"stringValue": sb_path},
        "status":         {"stringValue": "ready"},
    }}
    r = requests.patch(url, json=body, headers=_fs_headers(token), timeout=10)
    r.raise_for_status()

# ── Screenshot capture ─────────────────────────────────────────────────────────

def _list_monitors() -> "list[tuple[int, str]]":
    """Enumerate available monitors. Returns [(index, label), ...] where index is
    the position in mss().monitors (1+; 0 is the virtual all-displays bounds)."""
    try:
        with mss.mss() as sct:
            monitors = sct.monitors
            out = []
            for i, m in enumerate(monitors[1:], start=1):
                w, h = m.get("width", 0), m.get("height", 0)
                left, top = m.get("left", 0), m.get("top", 0)
                is_primary = (left == 0 and top == 0)
                label = f"Monitor {i} — {w}×{h}" + ("  (Primary)" if is_primary else "")
                out.append((i, label))
            return out or [(1, "Primary monitor")]
    except Exception:
        return [(1, "Primary monitor")]


def _grab_jpeg() -> bytes:
    """Capture the configured monitor and return JPEG bytes at max quality.
    quality=100 keeps OCR-grade detail for hero portrait matching; without it,
    JPEG quantization can blur small features (rank icons, stat digits)."""
    monitor_index = max(1, int(_config.get("monitor_index", 1) or 1))
    with mss.mss() as sct:
        monitors = sct.monitors
        if monitor_index >= len(monitors):
            monitor_index = 1  # paired monitor was unplugged — fall back to primary
        shot = sct.grab(monitors[monitor_index])
        img = Image.frombytes("RGB", shot.size, shot.bgra, "raw", "BGRX")
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=100, subsampling=0, optimize=True)
    return buf.getvalue()

def _ts_label() -> str:
    return datetime.now().strftime("%H:%M:%S")

def _push_recent(icon: str, text: str):
    _recent.appendleft({"ts": _ts_label(), "icon": icon, "text": text})
    _refresh_recent_ui()

def _set_state(state_text: str, show_cancel: bool):
    if _tk_root is None:
        return
    def _update():
        if _sv_state:  _sv_state.set(state_text)
        if _cancel_btn:
            _cancel_btn.configure(state="normal" if show_cancel else "disabled")
    _tk_root.after(0, _update)

def _refresh_recent_ui():
    if _tk_root is None or _recent_frame is None:
        return
    def _update():
        for w in _recent_frame.winfo_children():
            w.destroy()
        if not _recent:
            ctk.CTkLabel(
                _recent_frame, text="No captures yet this session",
                text_color=FG_MUTED, font=("Segoe UI", 11), anchor="w", justify="left"
            ).pack(anchor="w", padx=16, pady=4)
            return
        for entry in _recent:
            ctk.CTkLabel(
                _recent_frame,
                text=f"{entry['ts']}   {entry['icon']}   {entry['text']}",
                text_color=FG_DIM, font=("Segoe UI", 11), anchor="w", justify="left",
            ).pack(anchor="w", padx=16, pady=2)
    _tk_root.after(0, _update)

def _do_capture():
    """State machine for two-phase capture. Runs in a background thread."""
    global _capture_state, _pending_doc_id, _pending_rank_url

    try:
        token = get_valid_token()
    except Exception as e:
        _push_recent("⚠", f"Auth error: {e}")
        _set_state("⚠️ Not paired", False)
        _show_toast("HeroIntel — Not paired", "Open Settings → Pair desktop.", level="error")
        _update_status_indicator()
        return

    uid = _config.get("uid", "")
    ts = int(time.time() * 1000)

    if _capture_state == "idle":
        _set_state("📸 Capturing rank progress...", False)
        try:
            jpeg = _grab_jpeg()
            path = f"users/{uid}/screenshots/{ts}_rank.jpg"
            url = upload_screenshot(jpeg, path, token)
            doc_id = create_pending_match(uid, url, path, token)
            _capture_state  = "waiting_scoreboard"
            _pending_doc_id = doc_id
            _pending_rank_url = url
            _push_recent("📸", "Rank captured — press hotkey on scoreboard")
            _set_state("⏳ Waiting for scoreboard...", True)
            _set_tray_variant("waiting")
            _show_toast("HeroIntel", "Rank captured — press hotkey on the scoreboard.")
        except Exception as e:
            _push_recent("⚠", f"Error: {e}")
            _set_state("⚠️ Ready", False)
            _show_toast("HeroIntel — Error", str(e)[:120], level="error")

    elif _capture_state == "waiting_scoreboard":
        _set_state("📸 Capturing scoreboard...", False)
        try:
            jpeg = _grab_jpeg()
            path = f"users/{uid}/screenshots/{ts}_scoreboard.jpg"
            url = upload_screenshot(jpeg, path, token)
            complete_pending_match(uid, _pending_doc_id, url, path, token)
            _capture_state  = "idle"
            _pending_doc_id = ""
            _push_recent("✓", "Match uploaded")
            _set_state("✅ Ready", False)
            _set_tray_variant("idle")
            _show_toast("HeroIntel", "Match captured! Check the web app to review.")
        except Exception as e:
            _push_recent("⚠", f"Error: {e}")
            _set_state("⚠️ Waiting for scoreboard...", True)
            _show_toast("HeroIntel — Error", str(e)[:120], level="error")

def on_hotkey():
    threading.Thread(target=_do_capture, daemon=True).start()

def on_cancel_hotkey():
    if _capture_state != "idle":
        cancel_pending()

# ── Cancel pending match ───────────────────────────────────────────────────────

def cancel_pending():
    global _capture_state, _pending_doc_id, _pending_rank_url
    if _capture_state == "idle":
        return
    _capture_state  = "idle"
    _pending_doc_id = ""
    _pending_rank_url = ""
    _push_recent("✕", "Capture cancelled")
    _set_state("✅ Ready", False)
    _set_tray_variant("idle")

# ── Toast notification ─────────────────────────────────────────────────────────

def _show_toast(title: str, message: str, *, level: str = "info"):
    """Show a Windows toast. Suppressed by user's notification preference:
       "all" (default) — every toast
       "errors"        — only level="error"
       "off"           — never
    """
    pref = (_config.get("notifications") or "all")
    if pref == "off":
        return
    if pref == "errors" and level != "error":
        return
    try:
        from plyer import notification  # type: ignore
        notification.notify(title=title, message=message, app_name=APP_NAME, timeout=4)
    except Exception:
        print(f"[{title}] {message}")

# ── Status home window ─────────────────────────────────────────────────────────

# Colors — exactly match web app CSS variables (src/app/globals.css)
BG        = "#0d0f14"
BG_RAISED = "#111318"
BG_CARD   = "#161b27"
BG_INPUT  = "#1e2535"
FG        = "#f3f4f6"
FG_DIM    = "#9ca3af"
FG_MUTED  = "#6b7280"
BORDER    = "#1f2433"
BLUE      = "#4d9de0"
ORANGE    = "#f4841e"
GREEN     = "#22c55e"
YELLOW    = "#eab308"
RED       = "#f87171"

def _format_instructions(hotkey: str) -> str:
    h = (hotkey or "f9").upper()
    return (
        f"1. Press {h} on the rank progress screen\n"
        f"2. Press {h} on the scoreboard screen\n"
        "    The web app auto-parses the match"
    )


def build_home_window(root: ctk.CTk, hotkey: str) -> tuple:
    root.title("HeroIntel Capture")
    root.geometry("520x600")
    root.minsize(520, 540)
    root.configure(fg_color=BG)
    root.protocol("WM_DELETE_WINDOW", root.withdraw)
    _apply_window_icon(root)

    sv_state  = tk.StringVar(value="✅ Ready")
    sv_status = tk.StringVar(value="● Connected")

    # ── Header ──
    hdr = ctk.CTkFrame(root, fg_color=BG_RAISED, corner_radius=0, height=68)
    hdr.pack(fill="x")
    hdr.pack_propagate(False)

    status_lbl = ctk.CTkLabel(hdr, textvariable=sv_status, text_color=GREEN,
                               font=("Segoe UI", 11))
    status_lbl.pack(side="right", padx=20, pady=20)

    logo_img = _get_wordmark_image(44)
    if logo_img is not None:
        ctk.CTkLabel(hdr, image=logo_img, text="").pack(side="left", padx=(20, 14), pady=12)
    ctk.CTkLabel(hdr, text="HeroIntel Capture", text_color=BLUE,
                 font=("Segoe UI", 18, "bold")).pack(side="left", pady=14)

    # ── State card ──
    card = ctk.CTkFrame(root, fg_color=BG_CARD, corner_radius=10,
                        border_width=1, border_color=BORDER)
    card.pack(fill="x", padx=16, pady=(16, 0))

    ctk.CTkLabel(card, text="STATUS", text_color=FG_DIM,
                 font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=20, pady=(16, 0))
    ctk.CTkLabel(card, textvariable=sv_state, text_color=FG,
                 font=("Segoe UI", 18, "bold")).pack(anchor="w", padx=20, pady=(4, 0))

    sv_instructions = tk.StringVar(value=_format_instructions(hotkey))
    ctk.CTkLabel(card, textvariable=sv_instructions, text_color=FG_DIM,
                 font=("Segoe UI", 14), justify="left").pack(
        anchor="w", padx=20, pady=(10, 20))

    # ── Recent captures ──
    recent_card = ctk.CTkFrame(root, fg_color=BG_CARD, corner_radius=10,
                               border_width=1, border_color=BORDER)
    recent_card.pack(fill="both", expand=True, padx=16, pady=(14, 0))
    ctk.CTkLabel(recent_card, text="RECENT", text_color=FG_DIM,
                 font=("Segoe UI", 10, "bold")).pack(anchor="w", padx=20, pady=(16, 6))
    recent_frame = ctk.CTkFrame(recent_card, fg_color=BG_CARD, corner_radius=0)
    recent_frame.pack(fill="both", expand=True, padx=4, pady=(0, 14))

    # ── Buttons ──
    btn_frame = ctk.CTkFrame(root, fg_color=BG, corner_radius=0)
    btn_frame.pack(fill="x", padx=16, pady=(14, 4))

    cancel_btn = ctk.CTkButton(
        btn_frame, text="Cancel capture", command=cancel_pending,
        fg_color="#3b1f1f", hover_color="#5c2a2a", text_color=RED,
        font=("Segoe UI", 12, "bold"),
        corner_radius=8, height=40, state="disabled"
    )
    cancel_btn.pack(side="left")

    ctk.CTkButton(
        btn_frame, text="Settings", command=lambda: _open_settings(root),
        fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
        font=("Segoe UI", 12),
        corner_radius=8, height=40, width=110
    ).pack(side="right")

    # Version footer
    foot = ctk.CTkFrame(root, fg_color=BG, corner_radius=0)
    foot.pack(fill="x", padx=16, pady=(2, 10))
    ctk.CTkLabel(foot, text=f"v{APP_VERSION}", text_color=FG_MUTED,
                 font=("Segoe UI", 9)).pack(side="left")

    return sv_state, sv_status, status_lbl, recent_frame, cancel_btn, sv_instructions


def _set_status_indicator(text: str, color: str):
    if _tk_root is None or _sv_status is None or _status_label is None:
        return
    def _update():
        if _sv_status: _sv_status.set(text)
        if _status_label: _status_label.configure(text_color=color)
    _tk_root.after(0, _update)


def _update_status_indicator():
    """Inspect token state and refresh the header badge accordingly."""
    rt = keyring.get_password(KEYRING_SERVICE, KEYRING_REFRESH_KEY)
    if not rt:
        _set_status_indicator("● Not paired", RED)
        return
    if _id_token and time.time() < _token_expiry:
        _set_status_indicator("● Connected", GREEN)
        return
    _set_status_indicator("● Reconnecting…", YELLOW)
    try:
        get_valid_token()
        _set_status_indicator("● Connected", GREEN)
    except Exception:
        _set_status_indicator("● Auth error", RED)


def _status_watcher():
    while True:
        try:
            _update_status_indicator()
        except Exception:
            pass
        time.sleep(30)


def _open_settings(root: ctk.CTk):
    global _config, _current_hotkey, _current_cancel_hotkey, _id_token, _token_expiry
    root.withdraw()
    new_cfg = run_settings_dialog(_config)
    if not new_cfg:
        root.deiconify()
        return

    # Apply autostart toggle (registry write happens regardless of other paths).
    autostart_requested = new_cfg.pop("_autostart", None)
    if autostart_requested is not None and autostart_requested != is_autostart_enabled():
        if not set_autostart(autostart_requested):
            messagebox.showwarning(
                "Start with Windows",
                "Couldn't update the auto-start registry entry. Try running as your "
                "user (not a different account) or check Group Policy.",
                parent=root,
            )

    # Sign out if requested — clear identity + force re-pair before continuing.
    if new_cfg.pop("_signout", False):
        try:
            keyring.delete_password(KEYRING_SERVICE, KEYRING_REFRESH_KEY)
        except Exception:
            pass
        _id_token = ""
        _token_expiry = 0.0
        new_cfg.pop("uid", None)
        new_cfg.pop("displayName", None)
        new_cfg.pop("email", None)
        # Force re-pair immediately so the user isn't stuck in an unauthenticated state
        paired = run_pairing_dialog(root)
        if not paired:
            # User cancelled — save the config without account info; status watcher
            # will surface "Not paired" until they re-pair via Settings.
            save_config(new_cfg)
            _config = new_cfg
            _update_status_indicator()
            root.deiconify()
            return
        new_cfg["uid"] = paired["uid"]
        new_cfg["displayName"] = paired.get("displayName", "")
        new_cfg["email"] = paired.get("email", "")

    # Re-pair if requested
    if new_cfg.pop("_repair", False):
        paired = run_pairing_dialog(root)
        if not paired:
            root.deiconify()
            return
        new_cfg["uid"] = paired["uid"]
        new_cfg["displayName"] = paired.get("displayName", "")
        new_cfg["email"] = paired.get("email", "")

    # Hotkey rebind
    new_hotkey = new_cfg.get("hotkey", "f9")
    new_cancel = new_cfg.get("cancel_hotkey", "")
    if new_hotkey != _current_hotkey:
        try:
            keyboard.remove_hotkey(_current_hotkey)
        except Exception:
            pass
        keyboard.add_hotkey(new_hotkey, on_hotkey, suppress=False)
        _current_hotkey = new_hotkey
        if _sv_instructions is not None:
            _sv_instructions.set(_format_instructions(new_hotkey))
    if new_cancel != _current_cancel_hotkey:
        if _current_cancel_hotkey:
            try:
                keyboard.remove_hotkey(_current_cancel_hotkey)
            except Exception:
                pass
        if new_cancel:
            try:
                keyboard.add_hotkey(new_cancel, on_cancel_hotkey, suppress=False)
            except Exception as e:
                messagebox.showwarning("Hotkey",
                    f"Couldn't bind cancel hotkey '{new_cancel}': {e}")
                new_cancel = ""
        _current_cancel_hotkey = new_cancel
        new_cfg["cancel_hotkey"] = new_cancel

    save_config(new_cfg)
    _config = new_cfg
    _rebuild_tray_menu()
    _update_status_indicator()
    root.deiconify()


# ── Pairing dialog ─────────────────────────────────────────────────────────────

def run_pairing_dialog(parent=None) -> "dict | None":
    """Modal dialog: shows pairing code, polls until claimed.
    Returns {uid, idToken, refreshToken} on success, or None on cancel/expiry.
    """
    global _id_token, _token_expiry

    dlg = ctk.CTkToplevel(parent) if parent else ctk.CTk()
    _prepare_dialog(dlg)  # alpha=0 + withdraw + dark titlebar + icon, before first paint
    dlg.title("HeroIntel Capture — Pair desktop")
    dlg.geometry("520x460")
    dlg.resizable(False, False)
    dlg.configure(fg_color=BG)

    # Tkinter is not thread-safe — the background pairing thread only mutates
    # this dict; the dialog drains pending UI updates from it via dlg.after().
    state_lock = threading.Lock()
    state = {
        "result": None,         # set on success: {"uid": ...}
        "stop": False,          # user clicked Cancel
        "pairing": None,        # current pairing init payload, or None to request a new code
        "pending_ui": None,     # next (text, color, code) to apply on the main thread
        "done": False,          # success — schedule destroy
        "abort_thread": False,  # tells the worker thread to exit without touching tk
    }

    # ── Header with logo ──
    hdr = ctk.CTkFrame(dlg, fg_color=BG_RAISED, corner_radius=0, height=72)
    hdr.pack(fill="x")
    hdr.pack_propagate(False)
    logo_img = _get_wordmark_image(44)
    if logo_img is not None:
        ctk.CTkLabel(hdr, image=logo_img, text="").pack(side="left", padx=(20, 14), pady=12)
    ctk.CTkLabel(hdr, text="Pair desktop", text_color=BLUE,
                 font=("Segoe UI", 18, "bold")).pack(side="left", pady=14)

    ctk.CTkLabel(dlg, text="Enter this code on the web app to connect this device:",
                 text_color=FG_DIM, font=("Segoe UI", 12), wraplength=480,
                 justify="left").pack(anchor="w", padx=20, pady=(20, 8))

    code_var = tk.StringVar(value="…")
    code_lbl = ctk.CTkLabel(dlg, textvariable=code_var, text_color=FG,
                            font=("Consolas", 36, "bold"))
    code_lbl.pack(pady=(8, 6))

    status_var = tk.StringVar(value="Requesting code…")
    status_lbl = ctk.CTkLabel(dlg, textvariable=status_var, text_color=FG_DIM,
                              font=("Segoe UI", 11))
    status_lbl.pack(pady=(0, 16))

    def copy_code():
        code = code_var.get()
        if code and code != "…":
            dlg.clipboard_clear()
            dlg.clipboard_append(code)

    def open_browser():
        webbrowser.open(_pairing_url("/pair"))

    btn_row = ctk.CTkFrame(dlg, fg_color=BG, corner_radius=0)
    btn_row.pack(fill="x", padx=20, pady=4)
    ctk.CTkButton(btn_row, text="Open pairing page", command=open_browser,
                  fg_color=ORANGE, hover_color="#e07010", text_color="white",
                  font=("Segoe UI", 12, "bold"), corner_radius=8, height=42).pack(
        side="left", expand=True, fill="x", padx=(0, 6))
    ctk.CTkButton(btn_row, text="Copy code", command=copy_code,
                  fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
                  font=("Segoe UI", 12), corner_radius=8, height=42).pack(
        side="left", expand=True, fill="x", padx=(6, 0))

    def cancel():
        with state_lock:
            state["stop"] = True
            state["abort_thread"] = True
        dlg.destroy()

    def request_new_code():
        with state_lock:
            state["pairing"] = None
            state["abort_thread"] = True  # tell current worker to exit
        code_var.set("…")
        status_var.set("Requesting code…")
        # Spawn fresh worker after a tick so the old one can notice abort.
        def _spawn():
            with state_lock:
                state["abort_thread"] = False
            threading.Thread(target=_do_pair, daemon=True).start()
        dlg.after(200, _spawn)

    foot = ctk.CTkFrame(dlg, fg_color=BG, corner_radius=0)
    foot.pack(fill="x", padx=20, pady=(12, 16))
    ctk.CTkButton(foot, text="Get a new code", command=request_new_code,
                  fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
                  font=("Segoe UI", 11), corner_radius=8, height=36).pack(side="left")
    ctk.CTkButton(foot, text="Cancel", command=cancel,
                  fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
                  font=("Segoe UI", 11), corner_radius=8, height=36).pack(side="right")

    def _post(text, color=None, code=None):
        """Thread-safe: queues a UI update for the main-thread poller to apply."""
        with state_lock:
            state["pending_ui"] = (text, color, code)

    def _drain_ui():
        """Runs on the main thread via dlg.after — applies queued updates."""
        try:
            with state_lock:
                update = state["pending_ui"]
                state["pending_ui"] = None
                done = state["done"]
            if update is not None:
                text, color, code = update
                if code is not None:
                    code_var.set(code)
                status_var.set(text)
                if color is not None:
                    status_lbl.configure(text_color=color)
            if done:
                dlg.after(900, dlg.destroy)
                return
            if state["stop"]:
                return
            dlg.after(120, _drain_ui)
        except tk.TclError:
            # Dialog destroyed — bail out silently.
            return

    def _do_pair():
        global _id_token, _token_expiry
        try:
            init = initiate_pairing()
        except Exception as e:
            _post(f"Could not request a code: {e}", RED)
            return
        with state_lock:
            if state["abort_thread"]:
                return
            state["pairing"] = init
        _post("Waiting for browser…", FG_DIM, code=init["code"])

        expires = init.get("expiresAt", "")
        try:
            expires_at = datetime.fromisoformat(expires.replace("Z", "+00:00")).timestamp()
        except Exception:
            expires_at = time.time() + 600

        while True:
            with state_lock:
                if state["stop"] or state["abort_thread"]:
                    return
            if time.time() > expires_at:
                _post("Code expired. Get a new one.", YELLOW)
                return
            try:
                res = poll_pairing(init["pairingToken"])
            except Exception:
                time.sleep(2)
                continue
            if res.get("status") == "claimed":
                custom_token = res["customToken"]
                uid = res["uid"]
                display_name = res.get("displayName", "") or ""
                email = res.get("email", "") or ""
                try:
                    id_token, refresh_token = sign_in_custom_token(custom_token)
                except Exception as e:
                    _post(f"Sign-in failed: {e}", RED)
                    return
                keyring.set_password(KEYRING_SERVICE, KEYRING_REFRESH_KEY, refresh_token)
                _id_token = id_token
                _token_expiry = time.time() + 3500
                with state_lock:
                    state["result"] = {"uid": uid, "displayName": display_name, "email": email}
                    state["done"] = True
                # Confirm the account on the dialog so the user sees who they paired as.
                if display_name or email:
                    _post(f"Paired as {display_name or email} ✓", GREEN)
                else:
                    _post("Paired ✓", GREEN)
                return
            if res.get("status") == "expired":
                _post("Code expired. Get a new one.", YELLOW)
                return
            time.sleep(2)

    threading.Thread(target=_do_pair, daemon=True).start()
    dlg.after(120, _drain_ui)

    if parent:
        dlg.transient(parent)
        dlg.grab_set()
        _position_near(dlg, parent)

    _reveal_dialog(dlg)

    dlg.wait_window()
    with state_lock:
        state["abort_thread"] = True
    return state["result"]


# ── Settings dialog ────────────────────────────────────────────────────────────

_NOTIFY_LABELS = [("All", "all"), ("Errors only", "errors"), ("Off", "off")]


def _section_header(parent, text):
    return ctk.CTkLabel(parent, text=text, text_color=FG_DIM,
                        font=("Segoe UI", 10, "bold"), anchor="w")


def _section_separator(parent):
    return ctk.CTkFrame(parent, fg_color=BORDER, height=1, corner_radius=0)


def run_settings_dialog(existing: dict) -> "dict | None":
    dlg = ctk.CTkToplevel(_tk_root) if _tk_root else ctk.CTk()
    _prepare_dialog(dlg)
    dlg.title("HeroIntel Capture — Settings")
    dlg.geometry("540x720")
    dlg.resizable(False, False)
    dlg.configure(fg_color=BG)

    # ── Header with logo ──
    hdr = ctk.CTkFrame(dlg, fg_color=BG_RAISED, corner_radius=0, height=64)
    hdr.pack(side="top", fill="x")
    hdr.pack_propagate(False)
    logo_img = _get_wordmark_image(36)
    if logo_img is not None:
        ctk.CTkLabel(hdr, image=logo_img, text="").pack(side="left", padx=(20, 14), pady=14)
    ctk.CTkLabel(hdr, text="Settings", text_color=BLUE,
                 font=("Segoe UI", 16, "bold")).pack(side="left", pady=14)

    # Save/Cancel row anchored to the bottom FIRST so body content can never
    # push it offscreen if the window ends up shorter than expected.
    btn_row = ctk.CTkFrame(dlg, fg_color=BG, corner_radius=0)
    btn_row.pack(side="bottom", fill="x", padx=20, pady=(8, 20))
    btn_row.columnconfigure(0, weight=1)
    btn_row.columnconfigure(1, weight=1)

    body = ctk.CTkFrame(dlg, fg_color=BG, corner_radius=0)
    body.pack(side="top", fill="both", expand=True, padx=20, pady=(14, 4))
    body.columnconfigure(0, weight=1)
    body.columnconfigure(1, weight=0)

    row = 0

    # ── HOTKEYS ──
    _section_header(body, "HOTKEYS").grid(row=row, column=0, columnspan=2, sticky="w", pady=(0, 6)); row += 1

    ctk.CTkLabel(body, text="Capture", text_color=FG, font=("Segoe UI", 12),
                 anchor="w", justify="left").grid(row=row, column=0, sticky="w", pady=4)
    hotkey_var = tk.StringVar(value=existing.get("hotkey", "f9"))
    ctk.CTkEntry(body, textvariable=hotkey_var, width=260, height=34,
                 font=("Segoe UI", 12),
                 fg_color=BG_INPUT, border_color=BORDER, text_color=FG,
                 corner_radius=8).grid(row=row, column=1, sticky="e", pady=4)
    row += 1

    ctk.CTkLabel(body, text="Cancel (optional)", text_color=FG, font=("Segoe UI", 12),
                 anchor="w", justify="left").grid(row=row, column=0, sticky="w", pady=4)
    cancel_var = tk.StringVar(value=existing.get("cancel_hotkey", ""))
    ctk.CTkEntry(body, textvariable=cancel_var, width=260, height=34, placeholder_text="e.g. f8",
                 font=("Segoe UI", 12),
                 fg_color=BG_INPUT, border_color=BORDER, text_color=FG,
                 corner_radius=8).grid(row=row, column=1, sticky="e", pady=4)
    row += 1

    _section_separator(body).grid(row=row, column=0, columnspan=2, sticky="ew", pady=(14, 12)); row += 1

    # ── CAPTURE ──
    _section_header(body, "CAPTURE").grid(row=row, column=0, columnspan=2, sticky="w", pady=(0, 6)); row += 1

    monitors = _list_monitors()
    monitor_labels = [label for _, label in monitors]
    monitor_label_to_index = {label: idx for idx, label in monitors}
    current_index = int(existing.get("monitor_index", 1) or 1)
    current_label = next((lbl for idx, lbl in monitors if idx == current_index), monitor_labels[0])
    monitor_var = tk.StringVar(value=current_label)

    ctk.CTkLabel(body, text="Monitor", text_color=FG, font=("Segoe UI", 12),
                 anchor="w", justify="left").grid(row=row, column=0, sticky="w", pady=4)
    ctk.CTkOptionMenu(body, values=monitor_labels, variable=monitor_var, width=260, height=34,
                      font=("Segoe UI", 11),
                      fg_color=BG_INPUT, button_color=BG_CARD, button_hover_color=BG_INPUT,
                      text_color=FG, dropdown_fg_color=BG_CARD, dropdown_text_color=FG,
                      dropdown_hover_color=BG_INPUT, corner_radius=8).grid(
        row=row, column=1, sticky="e", pady=4)
    row += 1

    _section_separator(body).grid(row=row, column=0, columnspan=2, sticky="ew", pady=(14, 12)); row += 1

    # ── BEHAVIOR ──
    _section_header(body, "BEHAVIOR").grid(row=row, column=0, columnspan=2, sticky="w", pady=(0, 6)); row += 1

    autostart_var = tk.BooleanVar(value=is_autostart_enabled())
    ctk.CTkCheckBox(body, text="Start with Windows", variable=autostart_var,
                    font=("Segoe UI", 12), text_color=FG,
                    fg_color=ORANGE, hover_color="#e07010",
                    border_color=BORDER, checkmark_color="white",
                    corner_radius=4).grid(row=row, column=0, columnspan=2, sticky="w", pady=4)
    row += 1

    ctk.CTkLabel(body, text="Notifications", text_color=FG, font=("Segoe UI", 12),
                 anchor="w", justify="left").grid(row=row, column=0, sticky="w", pady=4)
    notify_label_to_value = {label: value for label, value in _NOTIFY_LABELS}
    notify_value_to_label = {value: label for label, value in _NOTIFY_LABELS}
    notify_current = existing.get("notifications") or "all"
    notify_var = tk.StringVar(value=notify_value_to_label.get(notify_current, "All"))
    ctk.CTkOptionMenu(body, values=[label for label, _ in _NOTIFY_LABELS], variable=notify_var,
                      width=260, height=34, font=("Segoe UI", 11),
                      fg_color=BG_INPUT, button_color=BG_CARD, button_hover_color=BG_INPUT,
                      text_color=FG, dropdown_fg_color=BG_CARD, dropdown_text_color=FG,
                      dropdown_hover_color=BG_INPUT, corner_radius=8).grid(
        row=row, column=1, sticky="e", pady=4)
    row += 1

    _section_separator(body).grid(row=row, column=0, columnspan=2, sticky="ew", pady=(14, 12)); row += 1

    # ── ACCOUNT ──
    _section_header(body, "ACCOUNT").grid(row=row, column=0, columnspan=2, sticky="w", pady=(0, 6)); row += 1

    paired_uid = existing.get("uid", "")
    paired_name = existing.get("displayName", "")
    paired_email = existing.get("email", "")

    acct_text = ctk.CTkFrame(body, fg_color="transparent", corner_radius=0)
    acct_text.grid(row=row, column=0, sticky="w", pady=4)
    if paired_uid:
        primary = paired_name or paired_email or f"uid {paired_uid[:10]}…"
        ctk.CTkLabel(acct_text, text=primary, text_color=FG, font=("Segoe UI", 12, "bold"),
                     anchor="w", justify="left").pack(anchor="w")
        if paired_name and paired_email:
            ctk.CTkLabel(acct_text, text=paired_email, text_color=FG_MUTED,
                         font=("Segoe UI", 10), anchor="w", justify="left").pack(anchor="w")
    else:
        ctk.CTkLabel(acct_text, text="Not paired", text_color=FG_DIM, font=("Segoe UI", 12),
                     anchor="w", justify="left").pack(anchor="w")

    state = {"result": None}

    def collect_base() -> dict:
        return {
            **existing,
            "hotkey": hotkey_var.get().strip() or "f9",
            "cancel_hotkey": cancel_var.get().strip(),
            "monitor_index": monitor_label_to_index.get(monitor_var.get(), 1),
            "notifications": notify_label_to_value.get(notify_var.get(), "all"),
            "_autostart": bool(autostart_var.get()),
        }

    def repair():
        cfg = collect_base()
        cfg["_repair"] = True
        state["result"] = cfg
        dlg.destroy()

    def sign_out():
        if not messagebox.askyesno(
            "Sign out",
            "Sign out and forget this device's pairing?\n\n"
            "You'll need to pair again to capture matches.",
            parent=dlg,
        ):
            return
        cfg = collect_base()
        cfg["_signout"] = True
        state["result"] = cfg
        dlg.destroy()

    btn_col = ctk.CTkFrame(body, fg_color="transparent", corner_radius=0)
    btn_col.grid(row=row, column=1, sticky="ne", pady=4)
    ctk.CTkButton(btn_col, text="Re-pair", command=repair,
                  fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
                  font=("Segoe UI", 11), corner_radius=8, height=32, width=110).pack(
        anchor="e", pady=(0, 4))
    if paired_uid:
        ctk.CTkButton(btn_col, text="Sign out", command=sign_out,
                      fg_color="#3b1f1f", hover_color="#5c2a2a", text_color=RED,
                      font=("Segoe UI", 11), corner_radius=8, height=32, width=110).pack(
            anchor="e")
    row += 1

    def save():
        state["result"] = collect_base()
        dlg.destroy()

    # Populate the bottom-anchored btn_row created at the top of the function.
    ctk.CTkButton(btn_row, text="Save", command=save,
                  fg_color=ORANGE, hover_color="#e07010", text_color="white",
                  font=("Segoe UI", 12, "bold"), corner_radius=8, height=42).grid(
        row=0, column=0, sticky="ew", padx=(0, 6))
    ctk.CTkButton(btn_row, text="Cancel", command=dlg.destroy,
                  fg_color=BG_CARD, hover_color=BG_INPUT, text_color=FG_DIM,
                  font=("Segoe UI", 12), corner_radius=8, height=42).grid(
        row=0, column=1, sticky="ew", padx=(6, 0))

    if _tk_root:
        dlg.transient(_tk_root)
        dlg.grab_set()
        _position_near(dlg, _tk_root)

    _reveal_dialog(dlg)

    dlg.wait_window()
    return state["result"]


# ── Tray icon ──────────────────────────────────────────────────────────────────

def _make_icon_image(variant: str = "idle") -> Image.Image:
    path = _resource_path("icon.png")
    if path.exists():
        try:
            img = Image.open(path).convert("RGBA").resize((64, 64), Image.LANCZOS)
            if variant == "waiting":
                overlay = Image.new("RGBA", img.size, (244, 132, 30, 70))
                img = Image.alpha_composite(img, overlay)
            return img
        except Exception as e:
            print(f"[icon] failed to load {path}: {e}")
    # Asset missing — return a flat brand-color square (64×64) so pystray still works.
    color = (244, 132, 30, 255) if variant == "waiting" else (77, 157, 224, 255)
    return Image.new("RGBA", (64, 64), color)

def _set_tray_variant(variant: str):
    if _tray_icon is None:
        return
    try:
        _tray_icon.icon = _make_icon_image(variant)
    except Exception:
        pass

def _open_home(icon=None, _item=None):
    if _tk_root:
        _tk_root.after(0, _tk_root.deiconify)
        _tk_root.after(0, _tk_root.lift)

def _quit(icon, _item):
    icon.stop()
    keyboard.unhook_all()
    os._exit(0)

def _build_tray_menu() -> pystray.Menu:
    return pystray.Menu(
        item("Open", _open_home, default=True, visible=False),
        item(f"Capture ({_current_hotkey.upper()})", lambda i, it: on_hotkey()),
        item("Cancel pending", lambda i, it: cancel_pending(),
             enabled=lambda i: _capture_state != "idle"),
        item("Quit", _quit),
    )

def _rebuild_tray_menu():
    if _tray_icon is None:
        return
    try:
        _tray_icon.menu = _build_tray_menu()
    except Exception:
        pass

# ── Entry point ────────────────────────────────────────────────────────────────

def main():
    global _config
    global _tk_root, _sv_state, _sv_status, _status_label, _recent_frame, _cancel_btn, _sv_instructions
    global _tray_icon, _current_hotkey, _current_cancel_hotkey

    _config = load_config()

    _claim_app_identity()

    _tk_root = ctk.CTk()
    _tk_root.withdraw()

    # First-run: pair via web
    if not _config.get("uid") or not keyring.get_password(KEYRING_SERVICE, KEYRING_REFRESH_KEY):
        paired = run_pairing_dialog(_tk_root)
        if not paired:
            sys.exit(0)
        _config["uid"] = paired["uid"]
        _config["displayName"] = paired.get("displayName", "")
        _config["email"] = paired.get("email", "")
        _config.setdefault("hotkey", "f9")
        save_config(_config)

    _current_hotkey = _config.get("hotkey", "f9")
    _current_cancel_hotkey = _config.get("cancel_hotkey", "")

    _sv_state, _sv_status, _status_label, _recent_frame, _cancel_btn, _sv_instructions = build_home_window(
        _tk_root, _current_hotkey)
    _refresh_recent_ui()

    keyboard.add_hotkey(_current_hotkey, on_hotkey, suppress=False)
    if _current_cancel_hotkey:
        try:
            keyboard.add_hotkey(_current_cancel_hotkey, on_cancel_hotkey, suppress=False)
        except Exception as e:
            print(f"[hotkey] cancel hotkey failed: {e}")
            _current_cancel_hotkey = ""

    _tray_icon = pystray.Icon(APP_NAME, _make_icon_image("idle"), "HeroIntel Capture",
                              menu=_build_tray_menu())
    threading.Thread(target=_tray_icon.run, daemon=True).start()

    threading.Thread(target=_status_watcher, daemon=True).start()

    _show_toast("HeroIntel Capture", f"Running — press {_current_hotkey.upper()} after a match.")
    _tk_root.mainloop()


if __name__ == "__main__":
    main()
